version: 0.0
os: windows
files:
  - source: \
    destination: C:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: \before-install.ps1
      timeout: 1500
  AfterInstall:
    - location: \after-install.ps1
      timeout: 1500
