version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish -c release -o deploy-package
      - copy appspec.yml deploy-package/appspec.yml
      - copy before-install.ps1 deploy-package/before-install.ps1
      - copy after-install.ps1 deploy-package/after-install.ps1
      - copy appsettings.yml deploy-package/appsettings.yml
artifacts:
  files:
    - '**/*'
  base-directory: deploy-package
